apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-go
  namespace: {{ .Values.namespace }}
  annotations:
    ingress.class: "haproxy"
spec:
  ingressClassName: ingress-go
  rules:
    - host: go-go.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: server-go
              port:
                number: 3000