appName: api

port: 3000

namespace: api

configmap:
  name: api
  data:
    CUSTOM_HEADER: "This app was deployed with helm!"

image1:
  name: lmhinnoc/vdt-api
  tag: latest

image2:
  name: lmhinnoc/vdt-db
  tag: latest
